#!/bin/sh
xrandr --output LVDS-1 --off --output VGA-1 --off --output DP-1 --off --output DP-2 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DP-3 --mode 1920x1080 --pos 1920x0 --rotate normal
i3-msg '[workspace="1"]' move workspace to output 'DP-2'
i3-msg '[workspace="2"]' move workspace to output 'DP-2'
i3-msg '[workspace="3"]' move workspace to output 'DP-2'
i3-msg '[workspace="4"]' move workspace to output 'DP-2'
i3-msg '[workspace="5"]' move workspace to output 'DP-3'
i3-msg '[workspace="6"]' move workspace to output 'DP-3'
i3-msg '[workspace="7"]' move workspace to output 'DP-3'
i3-msg '[workspace="8"]' move workspace to output 'DP-3'
i3-msg '[workspace="9"]' move workspace to output 'DP-3'
i3-msg '[workspace="10"]' move workspace to output 'DP-3'
i3-msg '[workspace="11"]' move workspace to output 'DP-2'
i3-msg '[workspace="12"]' move workspace to output 'DP-2'
i3-msg '[workspace="13"]' move workspace to output 'DP-2'
i3-msg '[workspace="14"]' move workspace to output 'DP-2'
i3-msg '[workspace="15"]' move workspace to output 'DP-2'
i3-msg '[workspace="16"]' move workspace to output 'DP-2'
i3-msg '[workspace="17"]' move workspace to output 'DP-2'
